//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAcc
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public string NormalSide { get; set; }
        public Nullable<decimal> OriginalBalance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public string AccountDescription { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string Visibility { get; set; }
    }
}
