//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class ChartOfAcc
    {
        [Required]
        public double AccountNumber { get; set; }
        [Required]
        public string AccountName { get; set; }
        [Required]
        public string AccountType { get; set; }
        [Required]
        public string NormalSide { get; set; }
        [Required]
        public decimal OriginalBalance { get; set; }
        [Required]
        public decimal CurrentBalance { get; set; }
        public string AccountDescription { get; set; }
        public bool Active { get; set; }
        [Required]

        public string CreatedBy { get; set; }
    }
}
