//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateUser
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Old_Passwords { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP_Code { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<int> Login_Amount { get; set; }
        public Nullable<int> Login_Fails { get; set; }
        public Nullable<bool> Account_Locked { get; set; }
        public Nullable<System.DateTime> Last_Signout { get; set; }
        public string Security_Question1 { get; set; }
        public string Answer_1 { get; set; }
        public string Security_Question2 { get; set; }
        public string Answer_2 { get; set; }
        public Nullable<short> Login_Attempts { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public Nullable<int> TotalOnline_Mins { get; set; }
    }
}
