//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<double> AccountNumber { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> EntryId { get; set; }
        public Nullable<int> FileId { get; set; }
        public string AccountantComment { get; set; }
        public string AccountantUsername { get; set; }
        public string ManagerUser { get; set; }
        public string AccountName { get; set; }
        public string Entry_Type { get; set; }
    }
}
