//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> Debit { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string EntryId { get; set; }
        public Nullable<int> FileId { get; set; }
        public string Comment { get; set; }
    }
}
