//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int TransactionID { get; set; }
        public string AccountantUsername { get; set; }
        public string ManagerUsername { get; set; }
        public string AccountantComment { get; set; }
        public string ManagerComment { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public string Status { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> EntryId { get; set; }
        public string Entry_Type { get; set; }
        public Nullable<int> PostReference { get; set; }
        public Nullable<decimal> BeforeBalance { get; set; }
        public Nullable<decimal> AfterBalance { get; set; }
    }
}
